spring:
  application:
    name: Architecture Evaluator - Backend
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/TestingDB
    username: postgres
    password: 1502
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://prod-db-server:5432/architecture_evaluator
    username: postgres
    password: 1502
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false